name: base_code
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #stated:
  flutter_bloc: ^9.1.0
  #network
  dio: ^5.3.2
  pretty_dio_logger: ^1.4.0
  #storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  #splash
  flutter_native_splash: ^2.4.0
  #language
  easy_localization: ^3.0.7+1
  #  hive: ^2.2.3
  #  hive_flutter: ^1.1.0
  #router
  go_router: ^15.0.0
  #init
  intl: ^0.19.0
  get_it: ^8.0.3
  flutter_lints: ^3.0.0
  #camera
  #  camera: ^0.11.0+1
  #  camera_android: ^0.10.9+6
  # permission
  permission_handler: ^11.0.0
  #image
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.3
  another_flushbar: ^1.12.30
  #Loading
  flutter_easyloading: ^3.0.5
  #  photo_view: ^0.15.0
  #  flutter_image_compress: ^2.0.4
  image_picker: ^1.0.4
  #  image: ^4.1.3
  #font
  google_fonts: ^6.1.0

  #
  package_info_plus: ^8.0.0
  #firebase
  #  firebase_crashlytics: ^4.0.1
  #  firebase_core: ^3.1.0
  #  firebase_storage: ^12.0.1
  #  firebase_messaging: ^15.0.1
  #  firebase_analytics: ^11.0.1
  #  firebase_performance: ^0.10.0+1
  #hash:
  crypto: ^3.0.6
  #flavor:
  flutter_flavorizr: ^2.3.0
flutter_native_splash:
  background_image: assets/images/splash_screen.png # android ko đc xem ios đc ko
  android_12:
    color: "#006C81"
    image: assets/images/splash_screen.png
  #    color: "#FFFFFF"
  #    image: assets/images/bsh_splash.png
  android: true
  fullscreen: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - lib/l10n/

flavors:
  dev:
    app:
      name: "App Dev"
    android:
      applicationId: "com.example.base_code.dev"
      icon: "assets/icons/dev_icon.png"
    ios:
      bundleId: "com.example.baseCode.dev"
      icon: "assets/icons/dev_icon.png"
  prod:
    app:
      name: "App Prod"
    android:
      applicationId: "com.example.base_code"
      icon: "assets/icons/prod_icon.png"
    ios:
      bundleId: "com.example.baseCode"
      icon: "assets/icons/prod_icon.png"
