name: base_code
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #stated:
  flutter_bloc: ^9.1.0
  #network
  dio: ^5.3.2
  pretty_dio_logger: ^1.4.0
  #storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  #  hive: ^2.2.3
  #  hive_flutter: ^1.1.0
  #notify
  another_flushbar: ^1.12.30
  #splash
  flutter_native_splash: ^2.4.0
  #language
  easy_localization: ^3.0.7+1
  #router
  go_router: ^15.0.0
  #init
  intl: ^0.19.0
  #  get_it: ^8.0.3
  #  flutter_lints: ^3.0.0
  #camera
  #  camera: ^0.11.0+1
  #  camera_android: ^0.10.9+6
  # permission
  permission_handler: ^11.0.0
  #image
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.3
  flutter_svg: ^2.1.0
  image_picker: ^1.0.4
  #  photo_view: ^0.15.0
  #  flutter_image_compress: ^2.0.4
  #  image: ^4.1.3
  #Loading
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.3.0
  #font
  google_fonts: ^6.1.0
  # Info app
  package_info_plus: ^8.0.0
  #firebase
  #  firebase_crashlytics: ^4.0.1
  #  firebase_core: ^3.1.0
  #  firebase_storage: ^12.0.1
  #  firebase_messaging: ^15.0.1
  #  firebase_analytics: ^11.0.1
  #  firebase_performance: ^0.10.0+1
  #hash:
  crypto: ^3.0.6
  #flavor:
  flutter_flavorizr: ^2.3.0
  #logo app:
  flutter_launcher_icons: ^0.14.3
  #video call:
  stringee_plugin: ^1.2.14
  uuid: ^4.2.1
  provider: ^6.0.5
  flutter_local_notifications: ^18.0.1
  dart_jsonwebtoken: ^2.17.0
  agora_rtc_engine: ^6.5.1

  #test:
  mockito: ^5.4.3
  bloc_test: ^10.0.0
  build_runner:
  test:
flutter_native_splash:
  background_image: assets/images/splash_screen.png # android ko đc xem ios đc ko
  android_12:
  #    color: "#FFFFFF"
  #    image: assets/images/splash_screen.png
  #    color: "#FFFFFF"
  #    image: assets/images/bsh_splash.png
  android: true
  fullscreen: true
  ios: true
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: true
    avoid_print: true
    prefer_single_quotes: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - lib/l10n/

flavors:
  dev:
    app:
      name: "App Dev"
    android:
      applicationId: "com.example.base_code.dev"
      icon: "assets/icons/dev_icon.png"
    ios:
      bundleId: "com.example.baseCode.dev"
      icon: "assets/icons/dev_icon.png"
  prod:
    app:
      name: "App Prod"
    android:
      applicationId: "com.example.base_code"
      icon: "assets/icons/prod_icon.png"
    ios:
      bundleId: "com.example.baseCode"
      icon: "assets/icons/prod_icon.png"
